RE-FIT/Re-Fit-Spring

build.gradle, src/main/resources/application.yml
1. JPA 및 Mysql 라이브러리 추가
2. mysql 연결
=> [chore]: DB Connect to Server

.github/workflows/CD.yml, Dockerfile, docker-compose.yml, dockerfile-nginx, nginx/conf.d/nginx.conf
=> [chore]: Deploy Automation

.github/workflows/CI.yml, src/main/java/com/umc/refit/domain/Member.java, src/main/java/com/umc/refit/web/controller/ApiController.java, src/main/java/com/umc/refit/web/repository/MemberRepository.java, src/main/resources/application.yml
Member 객체 저장 및 조회 API 테스트
CI/CD 배포 자동화 및 RDS 연결 테스트
=> [test]: ci/cd 배포 테스트 API 작성

src/main/java/com/umc/refit/web/config/CorsConfig.java
- corsFilter를 생성하여 cors 요청 허용 기능 추가
=> [feat]: cors 요청 허용 기능 추가

src/main/java/com/umc/refit/domain/dto/member/IdFindDto.java, src/main/java/com/umc/refit/domain/dto/member/ResEmailDto.java, src/main/java/com/umc/refit/domain/dto/member/ResIdFindDto.java, src/main/java/com/umc/refit/exception/ExceptionType.java, src/main/java/com/umc/refit/exception/handler/MemberExceptionHandler.java, src/main/java/com/umc/refit/exception/member/MemberException.java, src/main/java/com/umc/refit/web/controller/MemberController.java
- email로 회원 조회 후 반환
- 로그인 아이디 값 변환 후 반환
- 예외 처리 시 해당 이메일에 대한 정보 조회 불가 문제 수정
=> [feat]: 아이디 찾기 API 기능 구현

src/main/java/com/umc/refit/domain/dto/member/PasswordResetDto.java, src/main/java/com/umc/refit/web/controller/MemberController.java, src/main/java/com/umc/refit/web/repository/MemberRepository.java, src/main/java/com/umc/refit/web/service/EmailService.java, src/main/java/com/umc/refit/web/service/MemberService.java, src/main/resources/templates/passwordReset.html
- 아이디 찾기 조회 로직 수정
- 비밀번호 재설정 로직 구현 및 메일 전송 기능
- 정규 표현식에 맞춰 비밀번호 재설정 로직 구현
- 비밀번호 재설정 이메일 페이지 디자인 초안 구현
- 이메일 발송 후 회원 비밀번호 수정
=> [feat] 패스워드 재설정 API 기능 구현

.github/workflows/CD.yml, build.gradle, src/main/java/com/umc/refit/web/config/OAuth2ResourceServer.java, src/main/java/com/umc/refit/web/filter/authentication/JwtAuthenticationFilter.java, src/main/java/com/umc/refit/web/filter/authentication/JwtKakaoAuthenticationFilter.java, src/main/java/com/umc/refit/web/filter/authorization/JwtAuthorizationRsaFilter.java, src/main/java/com/umc/refit/web/filter/exception/CustomAuthenticationFailureHandler.java, src/main/java/com/umc/refit/web/service/RefreshTokenService.java, src/main/resources/application.yml
- RefreshToken 레디스에 저장, 조회, 삭제 기능 구현
- 실제 레디스 서버와 연동 테스트
=> [feat] RefreshToken 레디스에 저장하는 기능 추가

src/main/java/com/umc/refit/domain/dto/chat/OAuth2.java, src/main/java/com/umc/refit/exception/handler/MemberExceptionHandler.java, src/main/java/com/umc/refit/exception/member/TokenException.java, src/main/java/com/umc/refit/web/config/OAuth2ResourceServer.java, src/main/java/com/umc/refit/web/controller/MemberController.java, src/main/java/com/umc/refit/web/controller/OauthController.java, src/main/java/com/umc/refit/web/filter/authorization/JwtAuthorizationRsaFilter.java, src/main/java/com/umc/refit/web/service/EmailService.java, src/main/resources/templates/passwordReset.html, src/main/resources/templates/verificationCode.html
- Oauth2.0 엔드포인트 API
- 리프레쉬 토큰 재발급 API
- 로그인 및 회원가입 API 테스트 및 수정
- 이메일 디자인 수정
=> [feat]: Oauth2.0 엔드포인트 API 및 리프레쉬 토큰 재발급 API 기능 구현

.github/workflows/CD.yml, build.gradle, src/main/java/com/umc/refit/domain/dto/s3/ImageDto.java, src/main/java/com/umc/refit/web/service/S3UploadService.java, src/main/resources/application.yml
- aws s3 라이브러리 추가
- 멀티파트파일 s3 업로드 기능 구현
=> [Feat]: 이미지 업로드시 s3에 저장되는 기능 구현

src/main/java/com/umc/refit/domain/dto/community/ScrapDto.java, src/main/java/com/umc/refit/domain/entity/Scrap.java, src/main/java/com/umc/refit/web/controller/CommunityController.java, src/main/java/com/umc/refit/web/repository/ScrapRepository.java, src/main/java/com/umc/refit/web/service/CommunityService.java, src/main/java/com/umc/refit/web/service/ScrapService.java
1. 스크랩 기능 구현
2. 이미 스크랩된 게시글이면 스크랩 취소
=> [feat]: 커뮤니티 글 스크랩 API 기능 구현

src/main/java/com/umc/refit/domain/dto/community/BlockDto.java, src/main/java/com/umc/refit/domain/entity/Block.java, src/main/java/com/umc/refit/web/controller/BlockController.java, src/main/java/com/umc/refit/web/repository/BlockRepository.java, src/main/java/com/umc/refit/web/service/BlockService.java
1. 이미 차단한 사용자 차단 불가
2. 자기 자신은 차단 불가
=> [feat]: 사용자 차단 API 기능 구현

src/main/java/com/umc/refit/domain/dto/community/PostClickResponseDto.java, src/main/java/com/umc/refit/domain/entity/PostImage.java, src/main/java/com/umc/refit/web/controller/CommunityController.java, src/main/java/com/umc/refit/web/service/CommunityService.java
=> [feat]: 커뮤니티 글 조회 API 기능 구현

src/main/java/com/umc/refit/domain/dto/community/PostMainResponseDto.java, src/main/java/com/umc/refit/web/controller/CommunityController.java, src/main/java/com/umc/refit/web/repository/CommunityRepository.java, src/main/java/com/umc/refit/web/service/CommunityService.java
1. 선택한 카테고리에 맞는 게시글 목록 
2. 차단한 유저의 글 제외
=> [feat]: 커뮤니티 메인 화면 API 기능 구현

src/main/java/com/umc/refit/web/controller/CommunityController.java, src/main/java/com/umc/refit/web/service/CommunityService.java
=> [feat]: 커뮤니티 글 삭제 API 기능 구현

src/main/java/com/umc/refit/web/controller/CommunityController.java, src/main/java/com/umc/refit/web/repository/CommunityRepository.java, src/main/java/com/umc/refit/web/service/CommunityService.java, src/main/java/com/umc/refit/web/service/ReportMemService.java
* 검색 키워드를 포함하는 제목의 글 목록 반환
* 대소문자 구분x
ex) '나눔' 키워드 입력 시 검색 결과: '나눔해요', '나눔' 등
=> [feat]: 커뮤니티 글 검색 API 기능 구현

src/main/java/com/umc/refit/web/controller/MypageController.java, src/main/java/com/umc/refit/web/repository/CommunityRepository.java, src/main/java/com/umc/refit/web/service/CommunityService.java
=> [feat]: 마이페이지 내피드(구매) API 기능 구현

src/main/java/com/umc/refit/domain/dto/clothe/RegisterClosetRequestDto.java, src/main/java/com/umc/refit/domain/entity/Clothe.java, src/main/java/com/umc/refit/exception/ExceptionType.java, src/main/java/com/umc/refit/exception/clothe/ClotheException.java, src/main/java/com/umc/refit/exception/handler/ClotheExceptionHandler.java, src/main/java/com/umc/refit/web/controller/ClotheController.java, src/main/java/com/umc/refit/web/repository/ClosetRepository.java, src/main/java/com/umc/refit/web/service/ClotheService.java, src/main/resources/application.yml
- PR 제목 : 옷장 삭제 API
- PR 날짜 :2023/07/23
- PR 특이사항 : `id` 에 해당하는 옷장(Clothe) 삭제하는 API
=> [feat] : 옷장 삭제 API 구현

src/main/java/com/umc/refit/domain/dto/clothe/RegisterClosetRequestDto.java, src/main/java/com/umc/refit/domain/entity/Closet.java, src/main/java/com/umc/refit/exception/ExceptionType.java, src/main/java/com/umc/refit/exception/clothe/ClosetException.java, src/main/java/com/umc/refit/exception/handler/ClosetExceptionHandler.java, src/main/java/com/umc/refit/web/controller/ClotheController.java, src/main/java/com/umc/refit/web/repository/ClosetRepository.java, src/main/java/com/umc/refit/web/service/ClosetService.java, src/main/resources/application.yml
Reverts RE-FIT/Re-Fit-Spring#55
=> Revert "[feat] : 옷장 삭제 API 구현"

src/main/java/com/umc/refit/domain/dto/clothe/GetClotheListResponseDto.java, src/main/java/com/umc/refit/domain/dto/clothe/GetClotheResponseDto.java, src/main/java/com/umc/refit/domain/dto/clothe/RegisterClotheRequestDto.java, src/main/java/com/umc/refit/domain/dto/clothe/UpdateClotheRequestDto.java, src/main/java/com/umc/refit/domain/entity/Clothe.java, src/main/java/com/umc/refit/exception/ExceptionType.java, src/main/java/com/umc/refit/exception/clothe/ClotheException.java, src/main/java/com/umc/refit/exception/handler/ClotheExceptionHandler.java, src/main/java/com/umc/refit/web/controller/ClotheController.java, src/main/java/com/umc/refit/web/repository/ClosetRepository.java, src/main/java/com/umc/refit/web/service/ClotheService.java
- PR 제목 : 옷장 관련 추가 구현 및 리팩토링
- PR 날짜 : 2023/07/25
- PR 특이사항 : 다른  API 리팩토링 및 추가 구현은 기획에서 변동사항이 있어 추후 추가 작업 예정입니다 ❗️
=> [feat] : 옷장 관련 추가 구현 및 리팩토링

src/main/resources/static/address.html
=> [feat]: 카카오 우편번호 api 사용을 위한 html 파일 추가

src/main/java/com/umc/refit/domain/dto/clothe/UpdateClotheGoalRequestDto.java, src/main/java/com/umc/refit/domain/entity/Clothe.java, src/main/java/com/umc/refit/web/controller/ClotheController.java, src/main/java/com/umc/refit/web/service/ClotheService.java
- PR 제목 : 옷장 목표 수정 API
- PR 날짜 : 2023/07/31
- PR 내용 :  최적화 및 필드 데이터타입 수정
- [Closes] #63
=> [feat] : 옷장 목표 수정 API 

src/main/java/com/umc/refit/domain/entity/Clothe.java, src/main/java/com/umc/refit/exception/ExceptionType.java, src/main/java/com/umc/refit/web/controller/ClotheController.java, src/main/java/com/umc/refit/web/repository/ClosetRepository.java, src/main/java/com/umc/refit/web/service/ClotheService.java
- PR 제목 : 옷장 입기 API 구현
- PR 날짜 : 2023/07/31
- PR 내용 : 옷장 옷 입기 API 추가 구현 및 리팩토링
=> [feat] : 옷장 입기 API 구현

src/main/java/com/umc/refit/web/controller/MypageController.java, src/main/java/com/umc/refit/web/service/MyPageService.java
- PR 제목 : 마이 페이지 회원 정보 수정 이름(닉네임) 중복 여부 판단하는 API
- PR 날짜 : 2023/08/01
- PR 내용 : 중복 시 True / 중복 아닐 시 False 반환합니다.
=> [feat] : 마이 페이지 회원 정보 수정 이름(닉네임) 중복 여부 API 

src/main/java/com/umc/refit/domain/dto/clothe/GetClotheForestRandomQuestionResponseDto.java, src/main/java/com/umc/refit/domain/entity/Question.java, src/main/java/com/umc/refit/web/controller/ClotheController.java, src/main/java/com/umc/refit/web/repository/QuestionRepository.java, src/main/java/com/umc/refit/web/service/ClotheService.java
- PR 제목 : 숲 화면 질문 랜덤 조회 API
- PR 날짜 : 2023/08/04
- PR 내용 :
1. 나무 클릭시 넘어갈 때 해당 API 요청을 합니다.
2. 랜덤으로 조회하기 때문에 API 마다 쿼리가 2번 나가는데 쿼리 최적화 방안을 고려중입니다.
=> [feat] : 숲 화면 질문 랜덤 조회 API

src/main/java/com/umc/refit/domain/dto/clothe/ShowClotheMainRequestDto.java, src/main/java/com/umc/refit/domain/entity/Clothe.java, src/main/java/com/umc/refit/web/controller/ClotheController.java, src/main/java/com/umc/refit/web/repository/ClosetRepository.java, src/main/java/com/umc/refit/web/service/ClotheService.java
- PR 제목 : 옷장 전체 조회 리팩토링
- PR 날짜 : 2023/08/04
- PR 내용 : 기존 옷장 조회 API 를 리팩토링한 PR 입니다.
=> [refactor] : 옷장 전체 조회 리팩토링

src/main/java/com/umc/refit/web/controller/ClotheController.java, src/main/java/com/umc/refit/web/repository/ClosetRepository.java, src/main/java/com/umc/refit/web/service/ClotheService.java
- PR 제목 : 옷장 전체 조회 리팩토링 및 요청 수정
- PR 날짜 : 2023/08/05
- PR 내용 : 
1.  요청 방식 `Request Body` 에서 쿼리 스트링으로 변경
2. 페이징 방식 무한 스크롤 방식으로 변경
=> [refactor] : 요청 방식 변경에 따른 옷장 전체 조회 리팩토링

src/main/java/com/umc/refit/domain/dto/clothe/GetClotheListResponseDto.java, src/main/java/com/umc/refit/domain/entity/Clothe.java, src/main/java/com/umc/refit/web/controller/ClotheController.java, src/main/java/com/umc/refit/web/repository/ClosetRepository.java, src/main/java/com/umc/refit/web/service/ClotheService.java
- PR 제목 : 옷장 관련 리팩토링 및 프론트 요청 사항 반영
- PR 날짜 : 2023/08/07
- PR 내용 👍 
1. 조회 Response Dto 필드 추가 (`lastDate`)
2. NPE exception 해결
3. 코드 리팩토링
=> [refactor] : 옷장관련 리팩토링 및 요청 사항 반영

src/main/java/com/umc/refit/web/service/ClotheService.java, src/main/java/com/umc/refit/web/service/MyInfoService.java
- PR 제목 :  옷장 전체 조회 API 리팩토링(오류 수정)
- PR 날짜 : 2023/08/12
- PR 내용 : `d-day` 정렬 조회 시 `D-00` 인 경우 오름 차순 정렬로 변경 및 `가장 많이 입은 순` 정렬 방식 오류 수정
=> [refactor] : 옷장 전체 조회 API 리팩토링

.github/workflows/CD.yml, src/main/java/com/umc/refit/domain/dto/mypage/GetMyResponseDto.java, src/main/java/com/umc/refit/domain/entity/Member.java, src/main/java/com/umc/refit/web/controller/MemberController.java, src/main/java/com/umc/refit/web/controller/MypageController.java, src/main/resources/application.yml
=> [feat]: 회원 가입시 이미지 및 가입 날짜 추가

src/main/java/com/umc/refit/domain/dto/clothe/RegisterClotheRequestDto.java, src/main/java/com/umc/refit/web/controller/ClotheController.java, src/main/java/com/umc/refit/web/repository/ClosetRepository.java, src/main/java/com/umc/refit/web/service/ClotheService.java
- PR 제목 : 옷장 전체 조회 Member 필터링 로직 추가
- PR 날짜 : 2023/08/15
- PR 내용 : 전체 조회시 현재 로그인 되어 있는 회원의 옷장 조회하도록 수정
=> [refactor] : 옷장 전체 조회 Member 필터링 로직 추가

Dockerfile
=> [chore]: 도커 파일 설정 변경

src/main/java/com/umc/refit/web/service/ClotheService.java
- PR 제목 : 옷장 옷 조회 API 오류 수정(Final) 및 불필요한 주석 제거
- PR 날짜 : 2023/08/22
- PR 내용 :  
- 기획에서 정해진 `D +00(내림차순)`,`D-00(내림차순)`,`목표 미설정(최신순)`,`목표 달성(최신순)` 정렬 구현
- 최적화 부분에서 고민이 드나, 유저가 저장하는 옷장 데이터가 그리 많지 않아 성능 저하가 크지 않을 것이라고 기대합니다.
=> [refactor] : 옷장 옷 조회 API 오류 수정 및 불필요한 주석 제거

src/main/java/com/umc/refit/web/service/ClotheService.java
- PR 제목 :  옷장 옷 입기 하루에 한 카테고리는 한번 입기만 가능(2번 이상 x) 수정
- PR 날짜 : 2022/08/22
- PR 내용 : 2번 까지 허용하는 것에서 1번만 하나의 카테고리 옷 입는거 허용하도록 수정하였습니다.
=> [refactor] : 옷장 옷 입기 하루에 한 카테고리는 한번 입기만 가능(2번 이상 x) 로 리팩토링
